name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Debug secrets
      run: |
        echo "DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}"
        echo "DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}"
        echo "DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_REPO }}"

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_REPO }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > ${HOME}/.kube/config
        cat ${HOME}/.kube/config
    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/wisecow-deployment wisecow=${{ secrets.DOCKER_HUB_REPO }}:latest
        kubectl rollout status deployment/wisecow-deployment
